version: "1"

services:
  users-service:
    build:
      context: ./StudentAcquire.User.Service
      dockerfile: Dockerfile
    ports:
      - 6001:6001
      - 6000:6000
  listings-service:
    build:
      context: ./StudentAcquire.Listing.Service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
      - 5000:5000
  nginx:
    image: nginx
    ports:
      - "80:80"
  db-listings:
    image: "postgres"
    restart: "always"
    ports:
      - "5434:5432"

    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "nevski00"
      POSTGRES_DB: "studentacquire-listings"
  db-users:
    image: "postgres"
    restart: "always"
    ports:
      - "5434:5432"

    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "nevski00"
      POSTGRES_DB: "studentacquire-users"
