apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: studentacquire.com
      http:
        paths:
          - path: /api/listings
            pathType: Prefix
            backend:
              service:
                name: listings-clusterip-srv
                port:
                  number: 80
          - path: /api/u/listings
            pathType: Prefix
            backend:
              service:
                name: users-clusterip-srv
                port:
                  number: 80
