name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_listings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Go to Listing Service
      run: cd StudentAcquire.Listing.Service
    - name: Restore dependencies
      run: dotnet StudentAcquire.Listing.Service.sln restore
    - name: Build
      run: dotnet StudentAcquire.Listing.Service.sln build --no-restore
    - name: Test
      run: dotnet StudentAcquire.Listing.Service.sln test --no-build --verbosity normal
      
  build_users:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Go to Users Service
      run: cd StudentAcquire.User.Service
    - name: Restore dependencies
      run: dotnet StudentAcquire.Users.Service.sln restore
    - name: Build
      run: dotnet StudentAcquire.Users.Service.sln build --no-restore
    - name: Test
      run: dotnet StudentAcquire.Users.Service.sln test --no-build --verbosity normal
