name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_listings:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./StudentAcquire.Listing.Service/StudentAcquire.Listing.Service.sln
    - name: Build
      run: dotnet build --no-restore ./StudentAcquire.Listing.Service/StudentAcquire.Listing.Service.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./StudentAcquire.Listing.Service/StudentAcquire.Listing.Service.sln 
      
  build_users:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./StudentAcquire.User.Service/StudentAcquire.User.Service.sln
    - name: Build
      run: dotnet build --no-restore ./StudentAcquire.User.Service/StudentAcquire.User.Service.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./StudentAcquire.User.Service/StudentAcquire.User.Service.sln
